/* ============================================================
   sprites.js — tiny pixel-art renderer + sprite data.
   Sprites are arrays of strings; each char maps to a color via
   a shared palette. Spaces / "." are transparent.
   ============================================================ */

const PAL = {
  ".": null, " ": null,
  K: "#202020", // outline / black
  W: "#ffffff",
  S: "#9a9a9a", s: "#5a5a5a", // grays
  R: "#e0392b", r: "#a02018", // reds
  O: "#f08030", o: "#c25a12", // oranges
  Y: "#f8d030", y: "#d8a800", // yellows
  G: "#58c850", g: "#3a8a38", // greens
  B: "#5890f0", b: "#2858b0", // blues
  P: "#9858d8", p: "#f0a0c0", // purple / pink
  N: "#d8b070", n: "#9a6a30", // tan / brown
  C: "#f0e0b0", c: "#d8c088", // cream
  T: "#48c0b0", // teal
  L: "#a0e8f0", // light blue (water sheen)
  E: "#f87858", // light orange (belly)
};

function drawGrid(ctx, grid, x, y, scale, pal = PAL) {
  for (let r = 0; r < grid.length; r++) {
    const row = grid[r];
    for (let c = 0; c < row.length; c++) {
      const col = pal[row[c]];
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x + c * scale, y + r * scale, scale, scale);
    }
  }
}

/* ---- Pokémon battle sprites (~16 wide). Charming, not exact. ---- */
const MON_SPRITES = {
  bulbasaur: [
    "...gggg.....g...",
    "..gggggg...ggg..",
    ".gggGGGgg.ggGgg.",
    ".ggGGGGGgggGGgg.",
    "gKgGGGGGGGGGGgKg",
    "gKKGGCCCCCCGGKKg",
    "gGGCKCCCCKCGGGGg",
    ".GGCCCKKCCCGGG..",
    ".GGGCCCCCCGGGG..",
    "..GGGGGGGGGGG...",
    "..GGggGGGGggG...",
    "..gg..gggg..gg..",
    "..gg..g..g..gg..",
    "...g..g..g...g..",
  ],
  ivysaur: [
    "...pppp.....p...",
    "..pPPPPp...ppp..",
    ".pgGGGgp.pgGgp..",
    "gKgGGGGGgGGGGKg.",
    "gKGGGGGGGGGGGKg.",
    "gGGCCCCCCCCGGGg.",
    ".GCKCCCCCCKCGG..",
    ".GGCCCKKCCCGGG..",
    "..GGGGGGGGGGG...",
    "..GGggGGGGggG...",
    "..gg..gggg..gg..",
    "...g..g..g...g..",
  ],
  venusaur: [
    "..p.pp.pp.p.....",
    ".pPpPPpPPpPp....",
    "pgGGGGGGGGGGgp..",
    "gKGGGGGGGGGGGKg.",
    "gKGGGCCCCCGGGKg.",
    "gGGCCCCCCCCCGGg.",
    ".GCKCCCCCCKCGG..",
    ".GGGGGGGGGGGGG..",
    "GGggGGGGGGGGggG.",
    "gg...gg..gg...gg",
    ".g...g....g...g.",
  ],
  charmander: [
    ".....OOOO.......",
    "....OOOOOO....RR",
    "...OKOOOKO...RYR",
    "...OOOOOOO..RYR.",
    "...OOKKKOO.RYR..",
    "..OOOEEEOOORYR..",
    "..OOEEEEEOOOR...",
    "...OEEEEEOOO....",
    "...OOEEEOOOOO...",
    "....OOOOO.OOO...",
    "...OO..OO..O....",
    "..OO...OO.......",
  ],
  charmeleon: [
    "..R..OOOO....RR.",
    ".RYR.OOOOO..RYR.",
    "RYRO KOOOK ORYR.",
    ".OOOOOOOOOO RYR.",
    ".OOOEEEEEOOOOR..",
    ".OOEEEEEEEOOO...",
    "..OEEEEEEEOOOO..",
    "..OOEEEEEOOOOO..",
    "...OOEEEOOO.OO..",
    "...OO..OOO......",
    "..OO....OO......",
  ],
  charizard: [
    "B....OOOO.....RR",
    "BBB.OOOOOO...RYR",
    ".BBOKOOOOKO.RYR.",
    "..OOOOOOOOOORYR.",
    ".OOOEEEEEEOOOR..",
    "BOOEEEEEEEEOOB..",
    "BBOEEEEEEEEOBB..",
    ".OOOEEEEEOOOO...",
    "..OOEEEEEOOOO...",
    "..OO.OOO.OOO....",
    ".OO...O...OO....",
  ],
  squirtle: [
    "....BBBBB.......",
    "...BBBBBBB......",
    "..BBKBBBKBB.....",
    "..BBBBBBBBB.....",
    "..BBBWWWBBB.....",
    ".NNCnCCCnCNN....",
    ".NCCnCCCnCCN....",
    ".NCCCCCCCCCN....",
    ".NNCCCCCCCNN....",
    "..NNCCCCCNN.....",
    "..BB.....BB.....",
    ".BB.......BB....",
  ],
  wartortle: [
    "..L.BBBBB..L....",
    ".LLBBBBBBB.LL...",
    "..BBKBBBKBB.....",
    "..BBBBBBBBB.....",
    ".NBBBWWWBBBN....",
    ".NNCnCCCnCNN....",
    ".NCCnCCCnCCN....",
    ".NCCCCCCCCCN....",
    "..NCCCCCCCN.....",
    "..NNCCCCCNN.....",
    ".LBB.....BBL....",
    "LL.BB...BB..LL..",
  ],
  blastoise: [
    "..S.BBBBB..S....",
    ".SSSBBBBBBSSS...",
    "SS.BBKBBBKBB.SS.",
    "...BBBBBBBBB....",
    ".NSBBBWWWBBBSN..",
    ".NNCnCCCnCNNN...",
    ".NCCnCCCnCCN....",
    ".NCCCCCCCCCN....",
    ".SNCCCCCCCNS....",
    ".SSNCCCCCNSS....",
    ".S.BB...BB.S....",
  ],
  pidgey: [
    "......NN........",
    ".....NNNN.......",
    "....NCCCCN......",
    "...NCKCCKCN.....",
    "..ONCCCCCCN.....",
    "..ONNCCCCNNO....",
    "...NNCCCCNN.....",
    "...nNNCCNNn.....",
    "....nNNNNn......",
    ".....O..O.......",
  ],
  pidgeotto: [
    "....R.NN.R......",
    "...RRNNNNRR.....",
    "...RNCCCCNR.....",
    "..NCKCCKCN......",
    ".ONCCCCCCCNO....",
    ".ONNCCCCCNNO....",
    "..NNCCCCCNN.....",
    "..nNNCCCCNNn....",
    "...nNNNNNNn.....",
    "....O....O......",
  ],
  rattata: [
    "..P.......P.....",
    ".PpP.....PpP....",
    ".PPP.....PPP....",
    "..PPPPPPPPP.....",
    ".PPCKCCCKPPP....",
    ".PPCCWCCCPP.....",
    "..PCCCCCCP......",
    "..CCC..CCC......",
    "..C......C......",
  ],
  raticate: [
    ".N.........N....",
    "NnN.......NnN...",
    "NNN.......NNN...",
    ".NNNNNNNNNNN....",
    ".NNCKCCCKNNN....",
    ".NNCCWWCCNN.C...",
    "..NCCCCCCN.CC...",
    "..CCC..CCCC.....",
    "..C......C......",
  ],
  spearow: [
    "....n..nn.......",
    "...nNNNNNn......",
    "..nNCKCKCNn.....",
    "..NCCRRRCCN.....",
    "..NCCRRRCCN.....",
    "...NCCCCCN......",
    "...nNNNNNn......",
    "....n.O.O.n.....",
    ".....O...O......",
  ],
  caterpie: [
    "...G..G.........",
    "..GGGGGG........",
    ".GGKGGKGGGGG....",
    ".GGGGGGGGGGGGG..",
    ".YGGGGGGGGGGGY..",
    ".YGGGGGGGGGGGY..",
    "..GGGGGGGGGGG...",
    "...GG.GG.GG.....",
  ],
  metapod: [
    "....GGGGGG......",
    "...GGGGGGGG.....",
    "..GGGKGGKGGG....",
    "..GGGGGGGGGG....",
    "..gGGGGGGGGg....",
    "..gGGGGGGGGg....",
    "...gGGGGGGg.....",
    "....gGGGGg......",
  ],
  butterfree: [
    "W.W..PPPP..W.W..",
    ".WW.PpPPpP.WW...",
    "WWWWPKPPKPWWWW..",
    ".WW.PPPPPP.WW...",
    "W.WW.PPPP.WW.W..",
    "..WWW.PP.WWW....",
    ".W.WW.PP.WW.W...",
    "......PP........",
  ],
  weedle: [
    "......R.........",
    ".....RR.........",
    "....RRn.........",
    "...NNNNNN.......",
    "..NCCCCCCN......",
    "..NCKCCKCN......",
    "..NCCCCCCN......",
    "...NnnnnN.......",
    "..pNCCCCNp......",
    ".pNNCCCCNNp.....",
    ".pNCCnnCCNp.....",
    "..NCCCCCCN......",
    "...p.NN.p.......",
  ],
  kakuna: [
    "....YYYYY.......",
    "...YYYYYYY......",
    "..YYKYYKYY......",
    "..YYYYYYYY......",
    "..yYYYYYYy......",
    "..yYYYYYYy......",
    "...yYYYYy.......",
    "....yYYy........",
  ],
  beedrill: [
    "S.S..YYYY..S.S..",
    ".SS.YKYYKY.SS...",
    "SSS.YYYYYY.SSS..",
    "..S.yYYYYy.S....",
    "....YYByYY......",
    "...YYByyBYY.....",
    "..K..yYYy..K....",
    "..KK......KK....",
  ],
  oddish: [
    ".....G.G........",
    "....GGGGG.......",
    "...GGGGGGG......",
    "....G.G.G.......",
    "...BBBBBBB......",
    "..BBKBBBKBB.....",
    "..BBBWBWBBB.....",
    "..BBBBBBBBB.....",
    "...C.....C......",
  ],
  gloom: [
    "...O.O.O........",
    "..OOpOpOO.......",
    "..OOOpOOO.......",
    "...OOOOO........",
    "...BBBBBBB......",
    "..BBKBBBKBB.....",
    "..BBBpppBBB.....",
    "..BBBBBBBBB.....",
    "...C.....C......",
  ],
  zubat: [
    "P..P..P..P..P...",
    "PP.PPPPPP.PP....",
    ".PPPCWWCPPP.....",
    "PPPPPKKPPPPP....",
    "PPPPPCCPPPPP....",
    ".PP.PPPP.PP.....",
    "..P..PP..P......",
  ],
  golbat: [
    "P..PP..PP..P....",
    "PP.PPPPPPP.PP...",
    ".PPPCKKCPPPP....",
    "PPPPpRRpPPPPP...",
    "PPPPpRRpPPPPP...",
    ".PPPPCCCPPPP....",
    "..PP.PPP.PP.....",
    "...P..P..P......",
  ],
  pikachu: [
    "K....K....K.....",
    "KY...K....YK....",
    ".KYK.K..KYK.....",
    "..YYYKKYYY......",
    "..YKYYYYKYR.....",
    "..YYYRYRYYY.....",
    "...YYYYYYY......",
    "...YnY.YnY......",
    "..YY.....YY.....",
    "..K.......K.....",
  ],
  raichu: [
    "K....K.K....K...",
    ".KY..K.K..YK....",
    "..KYKK.KKYK.....",
    "...YYYKKYYY.....",
    "...OKYYYYKO.....",
    "...OYYRYRYO.....",
    "....YYYYYY......",
    "....OnY.YnO.....",
    "...OO.....OO....",
    "...K.......K....",
  ],
  geodude: [
    "....SSSSSS......",
    "...SSsSSsSS.....",
    "..SSSSSSSSSS....",
    "..SSKSSSSKSS....",
    "..SSSSSSSSSS....",
    "SSSSsSSSSsSSSS..",
    "SSS.SSSSSS.SSS..",
    ".....SSSS.......",
  ],
  graveler: [
    "..SSSSSSSSSS....",
    ".SSsSSSSSSsSS...",
    "SSSSSSSSSSSSSS..",
    "SSSKSSSSSSKSSS..",
    "SSSSSSSSSSSSSS..",
    "SsSSSSSSSSSSsS..",
    "S.SSSSSSSSSS.S..",
    "....SS..SS......",
  ],
};

/* Fallback: a tinted blob colored by the Pokémon's primary type. */
const TYPE_COLOR = {
  normal: "N", fire: "O", water: "B", grass: "G", electric: "Y",
  poison: "P", flying: "S", bug: "g", ground: "n", rock: "S", psychic: "P",
};
function fallbackMon(species) {
  const t = (DEX[species] && DEX[species].types[0]) || "normal";
  const c = TYPE_COLOR[t] || "N";
  return [
    "....CCCC....".replace(/C/g, c),
    "..CCCCCCCC..".replace(/C/g, c),
    ".CCKCCCCKCC.".replace(/[C]/g, c),
    ".CCCCCCCCCC.".replace(/C/g, c),
    ".CCCWCCWCCC.".replace(/C/g, c),
    ".CCCCCCCCCC.".replace(/C/g, c),
    "..CCCCCCCC..".replace(/C/g, c),
    "...CC..CC...".replace(/C/g, c),
  ];
}
function monSprite(species) {
  return MON_SPRITES[species] || fallbackMon(species);
}

/* ---- Rear (back) sprites shown for the player's active Pokémon. ----
   Original 4-shade art; falls back to the front sprite when undefined. */
const MON_BACK = {
  charmander: [
    "....OOOOOO....Y.",
    "...OOOOOOOO..YRY",
    "..OOOOOOOOOO.RYR",
    "..OOCCCCCCOO.YoY",
    "..OOOOOOOOOO.oOo",
    "..OOOOOOOOOOOoO.",
    "...OOOOOOOOOoO..",
    "...OOOOOOOOoO...",
    "..OOOOOOOOOO....",
    "..OOOoooooOOO...",
    "..OOOOOOOOOO....",
    "..OOOOOOOOOO....",
    "...OOO..OOO.....",
    "...oO....Oo.....",
    "...oo....oo.....",
  ],
  squirtle: [
    "....BBBBBB......",
    "...BBBBBBBB.....",
    "..BBBBBBBBBB....",
    "..BBLLLLLLBB....",
    "..BBBBBBBBBB....",
    "..NBBBBBBBBN....",
    ".NNCccccccNN....",
    ".NCcccccccCN....",
    ".NCccccccccN....",
    ".NNCccccccNN....",
    "..NNcccccNN.....",
    "..BBB..BBB......",
    "..bB....Bb......",
  ],
  bulbasaur: [
    "...gg.GGGG.gg...",
    "..ggGGGGGGGGgg..",
    "..gGGGGGGGGGGg..",
    "..gGGCCCCCCGGg..",
    ".gKGGGGGGGGGGKg.",
    ".gGGGGGGGGGGGGg.",
    "..GGGgggggGGGG..",
    "..GGGGGGGGGGGG..",
    "..GGGGGGGGGGGG..",
    "...GGG..GGGG....",
    "...gG....Gg.....",
    "...gg....gg.....",
  ],
};
function monBackSprite(species) {
  return MON_BACK[species] || monSprite(species);
}

/* ---- Overworld player sprite: 14x16, 4 directions, 2 walk frames. ---- */
/* R=cap, C=skin, B=shirt(blue), b=pants, K=outline. */
const PLAYER_SPRITES = {
  down: [
    [
      "...RRRR...",
      "..RRRRRR..",
      "..RCCCCR..",
      "..CKCKCC..",
      "..CCCCCC..",
      "...CCCC...",
      "..BBBBBB..",
      ".BBBBBBBB.",
      "B.BBBBBB.B",
      "..bb..bb..",
      "..bb..bb..",
      "..KK..KK..",
    ],
    [
      "...RRRR...",
      "..RRRRRR..",
      "..RCCCCR..",
      "..CKCKCC..",
      "..CCCCCC..",
      "...CCCC...",
      "..BBBBBB..",
      ".BBBBBBBB.",
      "B.BBBBBB.B",
      "...bbbb...",
      "..bb..bb..",
      "..KK..KK..",
    ],
  ],
  up: [
    [
      "...RRRR...",
      "..RRRRRR..",
      "..RRRRRR..",
      "..CCCCCC..",
      "..CCCCCC..",
      "...CCCC...",
      "..BBBBBB..",
      ".BBBBBBBB.",
      "B.BBBBBB.B",
      "..bb..bb..",
      "..bb..bb..",
      "..KK..KK..",
    ],
    [
      "...RRRR...",
      "..RRRRRR..",
      "..RRRRRR..",
      "..CCCCCC..",
      "..CCCCCC..",
      "...CCCC...",
      "..BBBBBB..",
      ".BBBBBBBB.",
      "B.BBBBBB.B",
      "...bbbb...",
      "..bb..bb..",
      "..KK..KK..",
    ],
  ],
  left: [
    [
      "..RRRR....",
      ".RRRRRR...",
      ".RCCCC....",
      ".CKCCC....",
      ".CCCCC....",
      "..CCCC....",
      ".BBBBB....",
      "BBBBBBB...",
      ".BBBBB....",
      "..bbb.....",
      "..bb......",
      "..KK......",
    ],
    [
      "..RRRR....",
      ".RRRRRR...",
      ".RCCCC....",
      ".CKCCC....",
      ".CCCCC....",
      "..CCCC....",
      ".BBBBB....",
      "BBBBBBB...",
      ".BBBBB....",
      "...bbb....",
      "....bb....",
      "....KK....",
    ],
  ],
  right: [
    [
      "....RRRR..",
      "...RRRRRR.",
      "....CCCCR.",
      "....CCCKC.",
      "....CCCCC.",
      "....CCCC..",
      "....BBBBB.",
      "...BBBBBBB",
      "....BBBBB.",
      ".....bbb..",
      "......bb..",
      "......KK..",
    ],
    [
      "....RRRR..",
      "...RRRRRR.",
      "....CCCCR.",
      "....CCCKC.",
      "....CCCCC.",
      "....CCCC..",
      "....BBBBB.",
      "...BBBBBBB",
      "....BBBBB.",
      "....bbb...",
      "....bb....",
      "....KK....",
    ],
  ],
};
