/**
 * Passive resource regeneration for every power type, plus out-of-combat health
 * regen:
 *  - Mana: regenerates continuously.
 *  - Energy: ticks up by a fixed amount on a fixed interval.
 *  - Rage: decays while out of combat (and is generated by damage in combat.ts).
 *  - Health: regenerates only while out of combat (simplified five-second rule).
 */

import {
  ENERGY_TICK_AMOUNT,
  ENERGY_TICK_INTERVAL_MS,
  RAGE_DECAY_PER_SEC,
} from "@wow/shared";
import { Combat, Power, Stats } from "../../ecs/components.js";
import type { System, GameContext } from "../context.js";

export class ResourceSystem implements System {
  readonly name = "ResourceSystem";

  update(ctx: GameContext): void {
    for (const id of ctx.world.query(Stats)) {
      const stats = ctx.world.get(id, Stats)!;
      if (stats.dead) continue;
      const inCombat = ctx.world.get(id, Combat)?.inCombat ?? false;

      // Out-of-combat health regen.
      if (!inCombat && stats.hpRegen > 0 && stats.hp < stats.maxHp) {
        stats.hp = Math.min(stats.maxHp, stats.hp + stats.hpRegen * ctx.dt);
      }

      const power = ctx.world.get(id, Power);
      if (power) this.regenPower(power, inCombat, ctx.dt);
    }
  }

  private regenPower(power: Power, inCombat: boolean, dt: number): void {
    switch (power.type) {
      case "mana":
        if (power.manaRegen > 0 && power.current < power.max) {
          power.current = Math.min(power.max, power.current + power.manaRegen * dt);
        }
        break;

      case "energy":
        power.tickAccumulator += dt * 1000;
        while (power.tickAccumulator >= ENERGY_TICK_INTERVAL_MS) {
          power.tickAccumulator -= ENERGY_TICK_INTERVAL_MS;
          power.current = Math.min(power.max, power.current + ENERGY_TICK_AMOUNT);
        }
        break;

      case "rage":
        if (!inCombat && power.current > 0) {
          power.current = Math.max(0, power.current - RAGE_DECAY_PER_SEC * dt);
        }
        break;
    }
  }
}
