"""initial schema

Revision ID: 265167889fd0
Revises: 
Create Date: 2026-07-29 23:54:04.098202
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '265167889fd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('order_submitted', 'order_filled', 'order_rejected', 'broker_disconnect', 'stale_data', 'daily_loss', 'drawdown', 'risk_violation', 'strategy_paused', 'reconciliation_mismatch', 'application_failure', 'kill_switch', 'live_mode_change', 'promotion', name='alert_kind', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_channels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_acknowledged'), 'alerts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_at'), 'alerts', ['at'], unique=False)
    op.create_index(op.f('ix_alerts_kind'), 'alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=400), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('missing_bar', 'duplicate_record', 'stale_quote', 'timestamp_inconsistency', 'adjustment_error', 'extreme_outlier', 'symbol_change', 'delisted', 'provider_disagreement', 'market_closed', 'ohlc_inconsistent', 'non_positive_price', 'provider_error', name='issue_kind', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', 'critical', name='issue_severity', native_enum=False, length=40), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_issues'))
    )
    op.create_index(op.f('ix_data_quality_issues_detected_at'), 'data_quality_issues', ['detected_at'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_kind'), 'data_quality_issues', ['kind'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_resolved'), 'data_quality_issues', ['resolved'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_severity'), 'data_quality_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_symbol'), 'data_quality_issues', ['symbol'], unique=False)
    op.create_table('economic_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='econ_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_indicators')),
    sa.UniqueConstraint('series_id', 'observation_date', 'provider', name='uq_econ_series_date')
    )
    op.create_index(op.f('ix_economic_indicators_observation_date'), 'economic_indicators', ['observation_date'], unique=False)
    op.create_index(op.f('ix_economic_indicators_series_id'), 'economic_indicators', ['series_id'], unique=False)
    op.create_table('ensemble_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_key', sa.String(length=60), nullable=False),
    sa.Column('weight', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('prev_weight', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('raw_score', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('correlation_penalty', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('turnover_penalty', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('regime_multiplier', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('evidence_trades', sa.Integer(), nullable=True),
    sa.Column('capped_by', sa.String(length=60), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ensemble_weights'))
    )
    op.create_index(op.f('ix_ensemble_weights_as_of'), 'ensemble_weights', ['as_of'], unique=False)
    op.create_index(op.f('ix_ensemble_weights_strategy_key'), 'ensemble_weights', ['strategy_key'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registry_version', sa.String(length=24), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=True),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='feat_quality', native_enum=False, length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots')),
    sa.UniqueConstraint('symbol', 'as_of', 'registry_version', name='uq_feature_symbol_asof')
    )
    op.create_index(op.f('ix_feature_snapshots_as_of'), 'feature_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_symbol'), 'feature_snapshots', ['symbol'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_class', sa.Enum('equity', 'etf', 'option', 'future', 'crypto', name='asset_class', native_enum=False, length=40), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('fractionable', sa.Boolean(), nullable=False),
    sa.Column('shortable', sa.Boolean(), nullable=False),
    sa.Column('easy_to_borrow', sa.Boolean(), nullable=False),
    sa.Column('is_leveraged_etf', sa.Boolean(), nullable=False),
    sa.Column('delisted_on', sa.Date(), nullable=True),
    sa.Column('renamed_to', sa.String(length=24), nullable=True),
    sa.Column('first_seen_on', sa.Date(), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='data_quality', native_enum=False, length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    op.create_index(op.f('ix_instruments_created_at'), 'instruments', ['created_at'], unique=False)
    op.create_index(op.f('ix_instruments_sector'), 'instruments', ['sector'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('live_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('account_identifier', sa.String(length=120), nullable=True),
    sa.Column('broker', sa.String(length=40), nullable=True),
    sa.Column('max_allocation_usd', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('phrase_matched', sa.Boolean(), nullable=False),
    sa.Column('env_flag_enabled', sa.Boolean(), nullable=False),
    sa.Column('preflight', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('failure_reasons', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_authorizations'))
    )
    op.create_index(op.f('ix_live_authorizations_at'), 'live_authorizations', ['at'], unique=False)
    op.create_index(op.f('ix_live_authorizations_granted'), 'live_authorizations', ['granted'], unique=False)
    op.create_table('loop_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='loop_mode', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='loop_status', native_enum=False, length=40), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('market_open', sa.Boolean(), nullable=True),
    sa.Column('regime', sa.Enum('risk_on', 'neutral', 'risk_off', name='loop_regime', native_enum=False, length=40), nullable=True),
    sa.Column('health_ok', sa.Boolean(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('candidates_considered', sa.Integer(), nullable=False),
    sa.Column('decisions_made', sa.Integer(), nullable=False),
    sa.Column('orders_submitted', sa.Integer(), nullable=False),
    sa.Column('orders_rejected', sa.Integer(), nullable=False),
    sa.Column('halted_reason', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loop_runs'))
    )
    op.create_index(op.f('ix_loop_runs_mode'), 'loop_runs', ['mode'], unique=False)
    op.create_index(op.f('ix_loop_runs_started_at'), 'loop_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_loop_runs_status'), 'loop_runs', ['status'], unique=False)
    op.create_table('market_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('early_close', sa.Boolean(), nullable=False),
    sa.Column('holiday_name', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_calendar'))
    )
    op.create_index(op.f('ix_market_calendar_session_date'), 'market_calendar', ['session_date'], unique=True)
    op.create_table('metric_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_samples'))
    )
    op.create_index('ix_metric_name_at', 'metric_samples', ['name', 'at'], unique=False)
    op.create_index(op.f('ix_metric_samples_at'), 'metric_samples', ['at'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='snap_mode', native_enum=False, length=40), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('long_market_value', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('short_market_value', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('gross_exposure', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('net_exposure', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('day_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('day_pnl_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('cumulative_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('high_water_mark', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('drawdown_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('open_orders', sa.Integer(), nullable=False),
    sa.Column('risk_state', sa.Enum('normal', 'warning', 'defensive_1', 'defensive_2', 'emergency', 'read_only', name='snap_risk_state', native_enum=False, length=40), nullable=False),
    sa.Column('sector_exposure', sa.JSON(), nullable=True),
    sa.Column('strategy_exposure', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_at'), 'portfolio_snapshots', ['at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_session_date'), 'portfolio_snapshots', ['session_date'], unique=False)
    op.create_index('ix_snapshot_mode_at', 'portfolio_snapshots', ['mode', 'at'], unique=False)
    op.create_table('provider_fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_fetch_log'))
    )
    op.create_index(op.f('ix_provider_fetch_log_at'), 'provider_fetch_log', ['at'], unique=False)
    op.create_index(op.f('ix_provider_fetch_log_provider'), 'provider_fetch_log', ['provider'], unique=False)
    op.create_table('quarantines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('engaged_by', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarantines'))
    )
    op.create_index(op.f('ix_quarantines_active'), 'quarantines', ['active'], unique=False)
    op.create_index(op.f('ix_quarantines_created_at'), 'quarantines', ['created_at'], unique=False)
    op.create_index(op.f('ix_quarantines_key'), 'quarantines', ['key'], unique=False)
    op.create_index(op.f('ix_quarantines_scope'), 'quarantines', ['scope'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='recon_mode', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('clean', 'breaks_found', 'failed', name='recon_status', native_enum=False, length=40), nullable=False),
    sa.Column('positions_checked', sa.Integer(), nullable=False),
    sa.Column('orders_checked', sa.Integer(), nullable=False),
    sa.Column('breaks', sa.JSON(), nullable=True),
    sa.Column('auto_healed', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_runs'))
    )
    op.create_index(op.f('ix_reconciliation_runs_at'), 'reconciliation_runs', ['at'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_resolved'), 'reconciliation_runs', ['resolved'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_status'), 'reconciliation_runs', ['status'], unique=False)
    op.create_table('regime_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.Enum('risk_on', 'neutral', 'risk_off', name='regime', native_enum=False, length=40), nullable=False),
    sa.Column('score', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('index_trend', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('vol_regime', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('breadth', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('credit', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('yield_curve', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regime_snapshots'))
    )
    op.create_index(op.f('ix_regime_snapshots_as_of'), 'regime_snapshots', ['as_of'], unique=True)
    op.create_table('risk_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_configs'))
    )
    op.create_index(op.f('ix_risk_configs_created_at'), 'risk_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_configs_is_active'), 'risk_configs', ['is_active'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('family', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('research', 'quarantined', 'validated', 'paper', 'live_eligible', 'live', 'paused', 'retired', name='strategy_status', native_enum=False, length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused_reason', sa.Text(), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    op.create_index(op.f('ix_strategies_created_at'), 'strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategies_key'), 'strategies', ['key'], unique=True)
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_switch_engaged', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_reason', sa.Text(), nullable=True),
    sa.Column('kill_switch_engaged_by', sa.String(length=255), nullable=True),
    sa.Column('kill_switch_engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('risk_state', sa.Enum('normal', 'warning', 'defensive_1', 'defensive_2', 'emergency', 'read_only', name='sys_risk_state', native_enum=False, length=40), nullable=False),
    sa.Column('risk_state_reason', sa.Text(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_reason', sa.Text(), nullable=True),
    sa.Column('recovery_requires_approval', sa.Boolean(), nullable=False),
    sa.Column('trading_halted_for_date', sa.Date(), nullable=True),
    sa.Column('halt_reason', sa.Text(), nullable=True),
    sa.Column('last_loop_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconcile_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broker_connected', sa.Boolean(), nullable=False),
    sa.Column('broker_last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_state'))
    )
    op.create_index(op.f('ix_system_state_created_at'), 'system_state', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', 'readonly', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('timeframe', sa.String(length=12), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adjustment', sa.Enum('raw', 'split_only', 'split_dividend', name='adjustment', native_enum=False, length=40), nullable=False),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='bar_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_bars_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bars')),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'ts', name='uq_bars_instrument_tf_ts')
    )
    op.create_index(op.f('ix_bars_instrument_id'), 'bars', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_bars_symbol'), 'bars', ['symbol'], unique=False)
    op.create_index('ix_bars_symbol_ts', 'bars', ['symbol', 'ts'], unique=False)
    op.create_index(op.f('ix_bars_ts'), 'bars', ['ts'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('action_type', sa.String(length=24), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('new_symbol', sa.String(length=24), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='ca_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_corporate_actions_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions')),
    sa.UniqueConstraint('symbol', 'action_type', 'ex_date', name='uq_corp_action_symbol_type_date')
    )
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_instrument_id'), 'corporate_actions', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_symbol'), 'corporate_actions', ['symbol'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=12), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='fund_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('revenue_yoy', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('eps', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('eps_yoy', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('fcf_yoy', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('cash', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('roic', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('ev_to_sales', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('accruals_ratio', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('recurring_revenue_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('rnd_expense', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('short_interest_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('insider_net_buy_usd', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_fundamentals_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamentals')),
    sa.UniqueConstraint('symbol', 'period_end', 'provider', name='uq_fund_symbol_period')
    )
    op.create_index(op.f('ix_fundamentals_instrument_id'), 'fundamentals', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_fundamentals_observed_at'), 'fundamentals', ['observed_at'], unique=False)
    op.create_index(op.f('ix_fundamentals_period_end'), 'fundamentals', ['period_end'], unique=False)
    op.create_index(op.f('ix_fundamentals_symbol'), 'fundamentals', ['symbol'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=24), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('sentiment', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('uncertainty', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('source_credibility', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('novelty', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('event_tags', sa.JSON(), nullable=True),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='news_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_news_items_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_items')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_news_provider_external')
    )
    op.create_index(op.f('ix_news_items_instrument_id'), 'news_items', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_symbol'), 'news_items', ['symbol'], unique=False)
    op.create_index('ix_news_symbol_published', 'news_items', ['symbol', 'published_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('strategy_key', sa.String(length=60), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('growth_score', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('signal_score', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('uncertainty', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_return', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_return_low', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_return_high', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_vol', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('downside_estimate', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('estimated_cost_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_holding_days', sa.Integer(), nullable=True),
    sa.Column('regime', sa.Enum('risk_on', 'neutral', 'risk_off', name='opp_regime', native_enum=False, length=40), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('opposing_evidence', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('feature_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='opp_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], name=op.f('fk_opportunities_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_opportunities_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_as_of'), 'opportunities', ['as_of'], unique=False)
    op.create_index(op.f('ix_opportunities_strategy_key'), 'opportunities', ['strategy_key'], unique=False)
    op.create_index(op.f('ix_opportunities_symbol'), 'opportunities', ['symbol'], unique=False)
    op.create_index('ix_opportunity_asof_rank', 'opportunities', ['as_of', 'rank'], unique=False)
    op.create_table('promotion_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_key', sa.String(length=60), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=False),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_promotion_records_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_records'))
    )
    op.create_index(op.f('ix_promotion_records_at'), 'promotion_records', ['at'], unique=False)
    op.create_index(op.f('ix_promotion_records_created_at'), 'promotion_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_promotion_records_strategy_id'), 'promotion_records', ['strategy_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('bid', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('ask', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('bid_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('ask_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('last', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='quote_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_quotes_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes')),
    sa.UniqueConstraint('symbol', 'provider', name='uq_quotes_symbol_provider')
    )
    op.create_index(op.f('ix_quotes_instrument_id'), 'quotes', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_quotes_observed_at'), 'quotes', ['observed_at'], unique=False)
    op.create_index(op.f('ix_quotes_symbol'), 'quotes', ['symbol'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('quarantined', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_stratver_strategy_ver')
    )
    op.create_index(op.f('ix_strategy_versions_created_at'), 'strategy_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.Column('strategy_keys', sa.JSON(), nullable=True),
    sa.Column('phase', sa.Enum('in_sample', 'validation', 'out_of_sample', 'paper', 'live', name='bt_phase', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='run_status', native_enum=False, length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('universe', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('cost_model', sa.JSON(), nullable=True),
    sa.Column('benchmark_symbol', sa.String(length=24), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('benchmark_metrics', sa.JSON(), nullable=True),
    sa.Column('regime_metrics', sa.JSON(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=True),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('uses_synthetic_data', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtest_runs_strategy_id_strategies')),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_backtest_runs_strategy_version_id_strategy_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs'))
    )
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_phase'), 'backtest_runs', ['phase'], unique=False)
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loop_run_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='decision_mode', native_enum=False, length=40), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', 'TRIM', 'ADD', 'EXIT', name='decision_action', native_enum=False, length=40), nullable=False),
    sa.Column('strategy_key', sa.String(length=60), nullable=True),
    sa.Column('strategy_version', sa.String(length=24), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('registry_version', sa.String(length=24), nullable=True),
    sa.Column('proposed_quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('approved_quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('proposed_notional', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('uncertainty', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_return', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_holding_days', sa.Integer(), nullable=True),
    sa.Column('risk_contribution', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('estimated_cost_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('regime', sa.Enum('risk_on', 'neutral', 'risk_off', name='dec_regime', native_enum=False, length=40), nullable=True),
    sa.Column('signal_inputs', sa.JSON(), nullable=True),
    sa.Column('entry_thesis', sa.Text(), nullable=True),
    sa.Column('exit_criteria', sa.JSON(), nullable=True),
    sa.Column('invalidating_conditions', sa.JSON(), nullable=True),
    sa.Column('bull_case', sa.Text(), nullable=True),
    sa.Column('bear_case', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('sizing_detail', sa.JSON(), nullable=True),
    sa.Column('approval_state', sa.Enum('auto_approved', 'pending_human', 'approved', 'rejected_by_risk', 'rejected_by_human', 'expired', name='approval_state', native_enum=False, length=40), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_verdict', sa.JSON(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('data_quality', sa.Enum('ok', 'suspect', 'stale', 'missing', 'corrupt', 'synthetic', name='dec_quality', native_enum=False, length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loop_run_id'], ['loop_runs.id'], name=op.f('fk_decisions_loop_run_id_loop_runs')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_decisions_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_approval_state'), 'decisions', ['approval_state'], unique=False)
    op.create_index('ix_decisions_at_symbol', 'decisions', ['decided_at', 'symbol'], unique=False)
    op.create_index(op.f('ix_decisions_decided_at'), 'decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_decisions_loop_run_id'), 'decisions', ['loop_run_id'], unique=False)
    op.create_index(op.f('ix_decisions_mode'), 'decisions', ['mode'], unique=False)
    op.create_index(op.f('ix_decisions_strategy_key'), 'decisions', ['strategy_key'], unique=False)
    op.create_index(op.f('ix_decisions_symbol'), 'decisions', ['symbol'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('strategy_key', sa.String(length=60), nullable=True),
    sa.Column('side', sa.Enum('buy', 'sell', name='bt_side', native_enum=False, length=40), nullable=False),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('costs', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('return_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=80), nullable=True),
    sa.Column('mae_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('mfe_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], name=op.f('fk_backtest_trades_run_id_backtest_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    op.create_index(op.f('ix_backtest_trades_run_id'), 'backtest_trades', ['run_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_symbol'), 'backtest_trades', ['symbol'], unique=False)
    op.create_table('equity_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('gross_exposure', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('net_exposure', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('benchmark_equity', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('regime', sa.Enum('risk_on', 'neutral', 'risk_off', name='eq_regime', native_enum=False, length=40), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], name=op.f('fk_equity_points_run_id_backtest_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equity_points'))
    )
    op.create_index(op.f('ix_equity_points_run_id'), 'equity_points', ['run_id'], unique=False)
    op.create_index('ix_equity_run_date', 'equity_points', ['run_id', 'session_date'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('replaces_order_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='order_mode', native_enum=False, length=40), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side', native_enum=False, length=40), nullable=False),
    sa.Column('order_type', sa.Enum('market', 'limit', 'stop', 'stop_limit', name='order_type', native_enum=False, length=40), nullable=False),
    sa.Column('time_in_force', sa.Enum('day', 'gtc', 'ioc', 'fok', 'opg', 'cls', name='tif', native_enum=False, length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('status', sa.Enum('pending_new', 'new', 'partially_filled', 'filled', 'pending_cancel', 'canceled', 'pending_replace', 'replaced', 'rejected', 'expired', name='order_status', native_enum=False, length=40), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_key', sa.String(length=60), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('expected_spread_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_slippage_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_impact_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('expected_total_cost_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('realized_slippage_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('broker', sa.String(length=40), nullable=True),
    sa.Column('submit_attempts', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_orders_decision_id_decisions')),
    sa.ForeignKeyConstraint(['replaces_order_id'], ['orders.id'], name=op.f('fk_orders_replaces_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_decision_id'), 'orders', ['decision_id'], unique=False)
    op.create_index(op.f('ix_orders_mode'), 'orders', ['mode'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_symbol', 'orders', ['status', 'symbol'], unique=False)
    op.create_index(op.f('ix_orders_strategy_key'), 'orders', ['strategy_key'], unique=False)
    op.create_index(op.f('ix_orders_submitted_at'), 'orders', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='position_mode', native_enum=False, length=40), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('last_price_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('peak_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_key', sa.String(length=60), nullable=True),
    sa.Column('entry_decision_id', sa.Integer(), nullable=True),
    sa.Column('entry_thesis', sa.Text(), nullable=True),
    sa.Column('exit_criteria', sa.JSON(), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('trailing_stop_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('risk_contribution', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('thesis_status', sa.String(length=24), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_decision_id'], ['decisions.id'], name=op.f('fk_positions_entry_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('mode', 'symbol', name='uq_positions_mode_symbol')
    )
    op.create_index(op.f('ix_positions_created_at'), 'positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_positions_mode'), 'positions', ['mode'], unique=False)
    op.create_index(op.f('ix_positions_strategy_key'), 'positions', ['strategy_key'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('post_trade_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('realized_return_pct', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('expected_vs_actual', sa.JSON(), nullable=True),
    sa.Column('thesis_outcome', sa.String(length=40), nullable=True),
    sa.Column('exit_reason', sa.String(length=80), nullable=True),
    sa.Column('slippage_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('cost_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('calibration_bucket', sa.String(length=24), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_post_trade_reviews_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_trade_reviews'))
    )
    op.create_index(op.f('ix_post_trade_reviews_at'), 'post_trade_reviews', ['at'], unique=False)
    op.create_index(op.f('ix_post_trade_reviews_decision_id'), 'post_trade_reviews', ['decision_id'], unique=True)
    op.create_index(op.f('ix_post_trade_reviews_symbol'), 'post_trade_reviews', ['symbol'], unique=False)
    op.create_table('risk_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_name', sa.String(length=80), nullable=False),
    sa.Column('result', sa.Enum('pass', 'warn', 'resize', 'reject', name='risk_result', native_enum=False, length=40), nullable=False),
    sa.Column('observed', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('limit_value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('utilization', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_risk_checks_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_checks'))
    )
    op.create_index(op.f('ix_risk_checks_at'), 'risk_checks', ['at'], unique=False)
    op.create_index(op.f('ix_risk_checks_check_name'), 'risk_checks', ['check_name'], unique=False)
    op.create_index(op.f('ix_risk_checks_decision_id'), 'risk_checks', ['decision_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='fill_side', native_enum=False, length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('slippage_bps', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('liquidity_flag', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_fills_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fills')),
    sa.UniqueConstraint('order_id', 'broker_fill_id', name='uq_fills_order_brokerfill')
    )
    op.create_index(op.f('ix_fills_at'), 'fills', ['at'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_symbol'), 'fills', ['symbol'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.Enum('pending_new', 'new', 'partially_filled', 'filled', 'pending_cancel', 'canceled', 'pending_replace', 'replaced', 'rejected', 'expired', name='oe_from', native_enum=False, length=40), nullable=True),
    sa.Column('to_status', sa.Enum('pending_new', 'new', 'partially_filled', 'filled', 'pending_cancel', 'canceled', 'pending_replace', 'replaced', 'rejected', 'expired', name='oe_to', native_enum=False, length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index(op.f('ix_order_events_at'), 'order_events', ['at'], unique=False)
    op.create_index(op.f('ix_order_events_event_type'), 'order_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_event_type'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_at'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_fills_symbol'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_at'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_risk_checks_decision_id'), table_name='risk_checks')
    op.drop_index(op.f('ix_risk_checks_check_name'), table_name='risk_checks')
    op.drop_index(op.f('ix_risk_checks_at'), table_name='risk_checks')
    op.drop_table('risk_checks')
    op.drop_index(op.f('ix_post_trade_reviews_symbol'), table_name='post_trade_reviews')
    op.drop_index(op.f('ix_post_trade_reviews_decision_id'), table_name='post_trade_reviews')
    op.drop_index(op.f('ix_post_trade_reviews_at'), table_name='post_trade_reviews')
    op.drop_table('post_trade_reviews')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_strategy_key'), table_name='positions')
    op.drop_index(op.f('ix_positions_mode'), table_name='positions')
    op.drop_index(op.f('ix_positions_created_at'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_submitted_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_key'), table_name='orders')
    op.drop_index('ix_orders_status_symbol', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_mode'), table_name='orders')
    op.drop_index(op.f('ix_orders_decision_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_equity_run_date', table_name='equity_points')
    op.drop_index(op.f('ix_equity_points_run_id'), table_name='equity_points')
    op.drop_table('equity_points')
    op.drop_index(op.f('ix_backtest_trades_symbol'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_decisions_symbol'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_strategy_key'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_mode'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_loop_run_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decided_at'), table_name='decisions')
    op.drop_index('ix_decisions_at_symbol', table_name='decisions')
    op.drop_index(op.f('ix_decisions_approval_state'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_phase'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_created_at'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_quotes_symbol'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_observed_at'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_instrument_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_promotion_records_strategy_id'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_created_at'), table_name='promotion_records')
    op.drop_index(op.f('ix_promotion_records_at'), table_name='promotion_records')
    op.drop_table('promotion_records')
    op.drop_index('ix_opportunity_asof_rank', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_symbol'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_strategy_key'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_as_of'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_news_symbol_published', table_name='news_items')
    op.drop_index(op.f('ix_news_items_symbol'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_instrument_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_fundamentals_symbol'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_period_end'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_observed_at'), table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_instrument_id'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_corporate_actions_symbol'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_instrument_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_bars_ts'), table_name='bars')
    op.drop_index('ix_bars_symbol_ts', table_name='bars')
    op.drop_index(op.f('ix_bars_symbol'), table_name='bars')
    op.drop_index(op.f('ix_bars_instrument_id'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_state_created_at'), table_name='system_state')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_key'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_created_at'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_risk_configs_is_active'), table_name='risk_configs')
    op.drop_index(op.f('ix_risk_configs_created_at'), table_name='risk_configs')
    op.drop_table('risk_configs')
    op.drop_index(op.f('ix_regime_snapshots_as_of'), table_name='regime_snapshots')
    op.drop_table('regime_snapshots')
    op.drop_index(op.f('ix_reconciliation_runs_status'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_resolved'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_at'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_quarantines_scope'), table_name='quarantines')
    op.drop_index(op.f('ix_quarantines_key'), table_name='quarantines')
    op.drop_index(op.f('ix_quarantines_created_at'), table_name='quarantines')
    op.drop_index(op.f('ix_quarantines_active'), table_name='quarantines')
    op.drop_table('quarantines')
    op.drop_index(op.f('ix_provider_fetch_log_provider'), table_name='provider_fetch_log')
    op.drop_index(op.f('ix_provider_fetch_log_at'), table_name='provider_fetch_log')
    op.drop_table('provider_fetch_log')
    op.drop_index('ix_snapshot_mode_at', table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_session_date'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_metric_samples_at'), table_name='metric_samples')
    op.drop_index('ix_metric_name_at', table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index(op.f('ix_market_calendar_session_date'), table_name='market_calendar')
    op.drop_table('market_calendar')
    op.drop_index(op.f('ix_loop_runs_status'), table_name='loop_runs')
    op.drop_index(op.f('ix_loop_runs_started_at'), table_name='loop_runs')
    op.drop_index(op.f('ix_loop_runs_mode'), table_name='loop_runs')
    op.drop_table('loop_runs')
    op.drop_index(op.f('ix_live_authorizations_granted'), table_name='live_authorizations')
    op.drop_index(op.f('ix_live_authorizations_at'), table_name='live_authorizations')
    op.drop_table('live_authorizations')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_sector'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_created_at'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_feature_snapshots_symbol'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_as_of'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_ensemble_weights_strategy_key'), table_name='ensemble_weights')
    op.drop_index(op.f('ix_ensemble_weights_as_of'), table_name='ensemble_weights')
    op.drop_table('ensemble_weights')
    op.drop_index(op.f('ix_economic_indicators_series_id'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_observation_date'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    op.drop_index(op.f('ix_data_quality_issues_symbol'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_severity'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_resolved'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_kind'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_detected_at'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_kind'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
