"""Overview, portfolio and risk-centre endpoints."""

from __future__ import annotations

from datetime import timedelta
from decimal import Decimal
from typing import Any

from fastapi import APIRouter, Depends, Query
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from aegisquant.api.security import CurrentUser, require_viewer
from aegisquant.config import RiskLimits, get_settings
from aegisquant.data import quality as Q
from aegisquant.data.registry import provider_health
from aegisquant.db import enums as E
from aegisquant.db.models import (
    Instrument,
    PortfolioSnapshot,
    ReconciliationRun,
    RegimeSnapshot,
    RiskCheck,
)
from aegisquant.db.repo import (
    current_mode,
    get_active_risk_config,
    get_system_state,
    latest_snapshot,
    open_orders,
    open_positions,
)
from aegisquant.db.session import get_session
from aegisquant.execution.broker.base import BrokerError
from aegisquant.execution.broker.factory import get_broker
from aegisquant.utils.money import ZERO, D, safe_div
from aegisquant.utils.timeutil import to_display, utcnow

router = APIRouter(tags=["dashboard"])


def _limits(session: Session) -> RiskLimits:
    row = get_active_risk_config(session)
    if row is None:
        return get_settings().risk
    try:
        return RiskLimits(**row.limits)
    except Exception:
        return get_settings().risk


def _dec(value: Any) -> str | None:
    return None if value is None else str(value)


@router.get("/overview")
def overview(user: CurrentUser = Depends(require_viewer), session: Session = Depends(get_session)) -> dict[str, Any]:
    """Everything the Overview screen needs in one call."""
    settings = get_settings()
    mode = current_mode()
    state = get_system_state(session)
    snapshot = latest_snapshot(session, mode)
    limits = _limits(session)

    account: dict[str, Any] = {"source": "snapshot"}
    try:
        broker = get_broker()
        broker_account = broker.get_account()
        account = {
            "source": "broker",
            "account_identifier": broker_account.masked_account_id,
            "is_paper": broker_account.is_paper,
            "equity": str(broker_account.equity),
            "cash": str(broker_account.cash),
            "buying_power": str(broker_account.buying_power),
            "trading_blocked": broker_account.trading_blocked,
            "day_trade_count": broker_account.day_trade_count,
        }
        broker_health = broker.health()
    except BrokerError as exc:
        broker_health = {"broker": settings.broker, "ok": False, "error": exc.message}
    except Exception as exc:  # never let the dashboard 500 on a broker problem
        broker_health = {"broker": settings.broker, "ok": False, "error": str(exc)[:200]}

    if account.get("source") != "broker" and snapshot is not None:
        account.update(
            {
                "equity": str(snapshot.equity),
                "cash": str(snapshot.cash),
                "buying_power": _dec(snapshot.buying_power),
            }
        )

    regime = session.scalar(select(RegimeSnapshot).order_by(RegimeSnapshot.as_of.desc()).limit(1))
    issues = Q.open_issue_summary(session)
    recon = session.scalar(select(ReconciliationRun).order_by(ReconciliationRun.at.desc()).limit(1))
    positions = open_positions(session, mode)

    # Cumulative P&L across the recorded history of this mode.
    first_snapshot = session.scalar(
        select(PortfolioSnapshot).where(PortfolioSnapshot.mode == mode).order_by(PortfolioSnapshot.at).limit(1)
    )
    cumulative_pnl = None
    if snapshot and first_snapshot:
        cumulative_pnl = str(snapshot.equity - first_snapshot.equity)

    return {
        "mode": mode.value,
        "config": settings.public_dict(),
        "data_disclaimer": (
            "SIMULATED MARKET DATA — figures below are generated by the built-in market "
            "simulator and are not real market history or real performance."
            if settings.price_provider == "fixture"
            else None
        ),
        "account": account,
        "pnl": {
            "day": _dec(snapshot.day_pnl) if snapshot else None,
            "day_pct": _dec(snapshot.day_pnl_pct) if snapshot else None,
            "cumulative": cumulative_pnl,
            "high_water_mark": _dec(snapshot.high_water_mark) if snapshot else None,
            "drawdown_pct": _dec(snapshot.drawdown_pct) if snapshot else None,
        },
        "exposure": {
            "gross": _dec(snapshot.gross_exposure) if snapshot else None,
            "net": _dec(snapshot.net_exposure) if snapshot else None,
            "long_market_value": _dec(snapshot.long_market_value) if snapshot else None,
            "open_positions": len(positions),
            "open_orders": len(open_orders(session, mode)),
            "max_gross": str(limits.max_gross_exposure_pct),
        },
        "regime": {
            "regime": regime.regime.value if regime else None,
            "score": _dec(regime.score) if regime else None,
            "as_of": regime.as_of.isoformat() if regime else None,
            "explanation": regime.explanation if regime else None,
            "components": regime.components if regime else None,
        },
        "health": {
            "providers": provider_health(),
            "broker": broker_health,
            "data_quality": issues,
            "reconciliation": {
                "status": recon.status.value if recon else None,
                "at": recon.at.isoformat() if recon else None,
                "breaks": (recon.breaks or {}).get("count", 0) if recon else None,
                "resolved": recon.resolved if recon else None,
            },
            "last_loop_at": state.last_loop_at.isoformat() if state.last_loop_at else None,
        },
        "controls": {
            "kill_switch_engaged": state.kill_switch_engaged,
            "kill_switch_reason": state.kill_switch_reason,
            "read_only": state.read_only,
            "risk_state": state.risk_state.value,
            "risk_state_reason": state.risk_state_reason,
            "trading_halted_for_date": (
                state.trading_halted_for_date.isoformat() if state.trading_halted_for_date else None
            ),
            "halt_reason": state.halt_reason,
            "cooldown_until": state.cooldown_until.isoformat() if state.cooldown_until else None,
            "recovery_requires_approval": state.recovery_requires_approval,
        },
        "timezone": settings.timezone,
        "server_time_utc": utcnow().isoformat(),
        "server_time_local": to_display(utcnow(), settings.timezone).isoformat(),
    }


@router.get("/portfolio")
def portfolio(user: CurrentUser = Depends(require_viewer), session: Session = Depends(get_session)) -> dict[str, Any]:
    mode = current_mode()
    snapshot = latest_snapshot(session, mode)
    equity = snapshot.equity if snapshot else ZERO
    limits = _limits(session)
    rows = []
    for pos in open_positions(session, mode):
        inst = session.scalar(select(Instrument).where(Instrument.symbol == pos.symbol))
        price = pos.last_price or pos.avg_entry_price
        weight = safe_div(pos.quantity * price, equity) if equity else ZERO
        rows.append(
            {
                "symbol": pos.symbol,
                "name": inst.name if inst else pos.symbol,
                "sector": (inst.sector if inst else None) or "Unclassified",
                "quantity": str(pos.quantity),
                "avg_entry_price": str(pos.avg_entry_price),
                "last_price": _dec(pos.last_price),
                "last_price_at": pos.last_price_at.isoformat() if pos.last_price_at else None,
                "market_value": _dec(pos.market_value),
                "cost_basis": str(pos.cost_basis),
                "unrealized_pnl": _dec(pos.unrealized_pnl),
                "unrealized_pnl_pct": _dec(pos.unrealized_pnl_pct),
                "realized_pnl": str(pos.realized_pnl),
                "weight": str(weight),
                "weight_limit": str(limits.max_position_pct),
                "risk_contribution": _dec(pos.risk_contribution),
                "strategy_key": pos.strategy_key,
                "entry_thesis": pos.entry_thesis,
                "exit_criteria": pos.exit_criteria,
                "stop_price": _dec(pos.stop_price),
                "trailing_stop_pct": _dec(pos.trailing_stop_pct),
                "peak_price": _dec(pos.peak_price),
                "thesis_status": pos.thesis_status,
                "opened_at": pos.opened_at.isoformat() if pos.opened_at else None,
                "holding_days": (utcnow() - pos.opened_at).days if pos.opened_at else None,
                "is_synthetic": pos.is_synthetic,
            }
        )
    rows.sort(key=lambda r: float(r["market_value"] or 0), reverse=True)

    history = list(
        session.scalars(select(PortfolioSnapshot).where(PortfolioSnapshot.mode == mode).order_by(PortfolioSnapshot.at))
    )
    return {
        "mode": mode.value,
        "equity": str(equity),
        "positions": rows,
        "sector_exposure": snapshot.sector_exposure if snapshot else {},
        "strategy_exposure": snapshot.strategy_exposure if snapshot else {},
        "equity_curve": [
            {
                "at": s.at.isoformat(),
                "session_date": s.session_date.isoformat(),
                "equity": str(s.equity),
                "cash": str(s.cash),
                "drawdown": _dec(s.drawdown_pct),
                "gross_exposure": str(s.gross_exposure),
                "positions": s.open_positions,
            }
            for s in history[-500:]
        ],
        # Also true when the price provider is the simulator, so the banner shows
        # on an empty book: `any()` over no positions is False, which would
        # otherwise present a fully simulated environment as if it were real.
        "using_synthetic_data": any(r["is_synthetic"] for r in rows) or get_settings().price_provider == "fixture",
    }


@router.get("/risk")
def risk_centre(user: CurrentUser = Depends(require_viewer), session: Session = Depends(get_session)) -> dict[str, Any]:
    """Current limits, utilisation, concentration, correlations and stress results."""
    from aegisquant.backtest.validation import stress_test
    from aegisquant.features.market_view import MarketView

    mode = current_mode()
    limits = _limits(session)
    snapshot = latest_snapshot(session, mode)
    state = get_system_state(session)
    equity = snapshot.equity if snapshot else ZERO
    positions = open_positions(session, mode)

    # --- utilisation of each portfolio-level limit ---
    gross = sum((p.quantity * (p.last_price or p.avg_entry_price) for p in positions), ZERO)
    sector_totals: dict[str, Decimal] = {}
    strategy_totals: dict[str, Decimal] = {}
    for pos in positions:
        inst = session.scalar(select(Instrument).where(Instrument.symbol == pos.symbol))
        sector = (inst.sector if inst else None) or "Unclassified"
        value = pos.quantity * (pos.last_price or pos.avg_entry_price)
        sector_totals[sector] = sector_totals.get(sector, ZERO) + value
        if pos.strategy_key:
            strategy_totals[pos.strategy_key] = strategy_totals.get(pos.strategy_key, ZERO) + value

    def util(observed: Decimal, limit: Decimal) -> dict[str, Any]:
        return {
            "observed": str(observed),
            "limit": str(limit),
            "utilization": str(safe_div(observed, limit)) if limit else None,
            "breached": bool(limit and observed > limit),
        }

    utilisation = {
        "gross_exposure": util(safe_div(gross, equity) if equity else ZERO, limits.max_gross_exposure_pct),
        "net_exposure": util(safe_div(gross, equity) if equity else ZERO, limits.max_net_exposure_pct),
        "open_positions": util(D(len(positions)), D(limits.max_open_positions)),
        "daily_loss": util(
            abs(snapshot.day_pnl_pct) if snapshot and snapshot.day_pnl_pct and snapshot.day_pnl_pct < 0 else ZERO,
            limits.max_daily_loss_pct,
        ),
        "drawdown": util(
            abs(snapshot.drawdown_pct) if snapshot and snapshot.drawdown_pct else ZERO,
            limits.max_portfolio_drawdown_pct,
        ),
        "cash_buffer": util(
            limits.min_cash_buffer_pct,
            safe_div(snapshot.cash, equity) if snapshot and equity else ZERO,
        ),
    }
    sector_util = {
        sector: util(safe_div(value, equity) if equity else ZERO, limits.max_sector_exposure_pct)
        for sector, value in sorted(sector_totals.items(), key=lambda kv: kv[1], reverse=True)
    }
    strategy_util = {
        key: util(safe_div(value, equity) if equity else ZERO, limits.max_strategy_exposure_pct)
        for key, value in sorted(strategy_totals.items(), key=lambda kv: kv[1], reverse=True)
    }

    # --- correlations among current holdings ---
    correlations: dict[str, Any] = {"pairs": [], "note": "insufficient history"}
    if len(positions) >= 2:
        try:
            import numpy as np

            symbols = [p.symbol for p in positions]
            view = MarketView.load(session, symbols, include_news=False, include_fundamentals=False)
            pit = view.at(utcnow())
            series = {}
            for symbol in symbols:
                closes = pit.closes(symbol, 90)
                if closes.size >= 40 and np.all(closes > 0):
                    series[symbol] = np.diff(np.log(closes))[-60:]
            pairs: list[dict[str, Any]] = []
            keys = sorted(series)
            for i, a in enumerate(keys):
                for b in keys[i + 1 :]:
                    n = min(series[a].size, series[b].size)
                    if n < 30:
                        continue
                    x, y = series[a][-n:], series[b][-n:]
                    if float(np.std(x)) == 0 or float(np.std(y)) == 0:
                        continue
                    value = float(np.corrcoef(x, y)[0, 1])
                    if np.isfinite(value):
                        pairs.append({"a": a, "b": b, "correlation": round(value, 4)})
            pairs.sort(key=lambda p: abs(float(p["correlation"])), reverse=True)
            above = [p for p in pairs if abs(float(p["correlation"])) > float(limits.correlation_threshold)]
            correlations = {
                "pairs": pairs[:40],
                "threshold": str(limits.correlation_threshold),
                "above_threshold": len(above),
                "average": (round(sum(abs(float(p["correlation"])) for p in pairs) / len(pairs), 4) if pairs else None),
                "note": None,
            }
        except Exception as exc:  # correlation is informational, never fatal
            correlations = {"pairs": [], "note": f"could not compute correlations: {exc}"}

    # --- stress test on the recorded equity curve ---
    history = list(
        session.scalars(select(PortfolioSnapshot).where(PortfolioSnapshot.mode == mode).order_by(PortfolioSnapshot.at))
    )
    stress: dict[str, Any] = {"note": "not enough portfolio history yet"}
    if len(history) >= 30:
        stress = stress_test(
            [float(s.equity) for s in history],
            beta=None,
            gross_exposure=float(safe_div(gross, equity)) if equity else None,
        )

    # --- recent risk-check activity ---
    recent_checks = list(
        session.scalars(
            select(RiskCheck)
            .where(
                RiskCheck.at >= utcnow() - timedelta(days=7),
                RiskCheck.result.in_([E.RiskCheckResult.REJECT, E.RiskCheckResult.RESIZE, E.RiskCheckResult.WARN]),
            )
            .order_by(RiskCheck.at.desc())
            .limit(100)
        )
    )
    breach_counts: dict[str, int] = {
        name: int(count)
        for name, count in session.execute(
            select(RiskCheck.check_name, func.count())
            .where(
                RiskCheck.at >= utcnow() - timedelta(days=30),
                RiskCheck.result == E.RiskCheckResult.REJECT,
            )
            .group_by(RiskCheck.check_name)
            .order_by(func.count().desc())
        ).all()
    }

    return {
        "limits": {k: str(v) for k, v in limits.model_dump().items()},
        "risk_state": state.risk_state.value,
        "risk_state_reason": state.risk_state_reason,
        "defensive_stages": {
            "warning": str(limits.drawdown_warning_pct),
            "defensive_1": str(limits.defensive_stage_1_pct),
            "defensive_2": str(limits.defensive_stage_2_pct),
            "emergency": str(limits.emergency_stage_pct),
            "current_drawdown": _dec(snapshot.drawdown_pct) if snapshot else None,
        },
        "utilisation": utilisation,
        "sector_utilisation": sector_util,
        "strategy_utilisation": strategy_util,
        "concentration": {
            "largest_position_weight": max(
                (str(safe_div(p.quantity * (p.last_price or p.avg_entry_price), equity)) for p in positions),
                default="0",
            )
            if equity
            else "0",
            "positions": len(positions),
            "sectors": len(sector_totals),
        },
        "correlations": correlations,
        "stress_test": stress,
        "recent_risk_events": [
            {
                "at": c.at.isoformat(),
                "check": c.check_name,
                "result": c.result.value,
                "message": c.message,
                "observed": _dec(c.observed),
                "limit": _dec(c.limit_value),
                "decision_id": c.decision_id,
            }
            for c in recent_checks
        ],
        "rejection_counts_30d": dict(breach_counts),
    }


@router.get("/risk/probabilities")
def drawdown_probabilities(
    user: CurrentUser = Depends(require_viewer),
    session: Session = Depends(get_session),
    lookback: int = Query(500, ge=60, le=5000),
) -> dict[str, Any]:
    """Bootstrapped drawdown and ruin probabilities from realised equity."""
    import numpy as np

    from aegisquant.backtest.metrics import _bootstrap_drawdown_probabilities, _returns

    mode = current_mode()
    history = list(
        session.scalars(
            select(PortfolioSnapshot.equity)
            .where(PortfolioSnapshot.mode == mode)
            .order_by(PortfolioSnapshot.at)
            .limit(lookback)
        )
    )
    if len(history) < 60:
        return {
            "available": False,
            "note": (
                f"only {len(history)} portfolio observations recorded; at least 60 are needed "
                "before drawdown probabilities mean anything"
            ),
        }
    equity = np.array([float(e) for e in history])
    probs = _bootstrap_drawdown_probabilities(_returns(equity))
    return {
        "available": True,
        "observations": len(history),
        **probs,
        "method": (
            "Stationary block bootstrap of realised daily returns over a one-year horizon. "
            "These are model estimates conditional on the return distribution continuing to "
            "resemble the past; they are not guarantees."
        ),
    }
